---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-agent
  namespace: drone
  labels:
    app: drone
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: drone-agent
#  labels:
#    app: drone
#subjects:
#  - kind: ServiceAccount
#    name: drone-agent
#    namespace: drone
#roleRef:
#  kind: ClusterRole
#  name: cluster-admin
#  apiGroup: rbac.authorization.k8s.io
